out	:	 mainhw2.o halfstring.o length.o hw2b.h
	gcc mainhw2.o halfstring.o length.o -o out
mainhw2.o	:	mainhw2.c
	gcc -c mainhw2.c
halfstring.o	:	halfstring.c
	gcc -c halfstring.c
length.o	:	length.c
	gcc -c length.c
clean:
	rm *.o out
