/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hw9 */

#ifndef _Included_hw9
#define _Included_hw9
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hw9
 * Method:    roundUp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hw9_roundUp
  (JNIEnv *, jobject, jint);

/*
 * Class:     hw9
 * Method:    convertFtoC
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_hw9_convertFtoC
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
