out	:	hw5main.o iofunctions.o myhw5functions.o account.h hw5header.h
	gcc  hw5main.o iofunctions.o myhw5functions.o -o out
hw5bmain.o :  hw5bmain.c
	gcc -c hw5main.c
iofunctions.o :    iofunctions.c
	gcc -c iofunctions.c
myhw5functions.o :    myhw5functions.c
	gcc -c myhw5functions.c
clean	:
	rm *.o out
